#!/bin/bash
uname=$1
pId=$2
img=$3
if [ "$(ls ../place_images | grep  $uname)" == "" ]; then
    echo 'uname not found'
    exit 1;
else
    mkdir ../place_images/$uname/$pId/
#    mv $img 0.jpg
#    mv $img ../place_images/$uname/$pId/
    exit 0;
fi
